### ISSUE TITLE
发送邮件

### ISSUE THREAD

**Issue by lzmvlog** [lzmvlog/comment#29]
https://www.lzmvlog.top/detail/%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6

**Comment by lzmvlog** [comment]
代码缺少了 yaml 中关于 邮件的配置 下次贴出来

**Comment by lzmvlog** [comment]
#这里使用springboot提供的邮箱服务
spring:
  mail:
    #    提供邮箱服务的地址
    host: smtp.163.com
    #    登录邮箱的账号
    username: zhang1591313226@163.com
    #    邮箱的授权码
    password: xxx
    #    发送的默认字符编码
    default-encoding: utf-8

**Comment by lzmvlog** [comment]
```yaml
#这里使用springboot提供的邮箱服务
spring:
  mail:
    #    提供邮箱服务的地址
    host: smtp.163.com
    #    登录邮箱的账号
    username: zhang1591313226@163.com
    #    邮箱的授权码
    password: xxx
    #    发送的默认字符编码
    default-encoding: utf-8
```
